### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.fedoraproject.org/projects/fedora-infra/noggin/) for fedora-infra/noggin.

### CODE REVIEW

**Comment by abompard** [comment]
Hey @Jibec , could Weblate be configured to add `Signed-off-by` to the commits?

**Comment by Jibec** [comment]
Yes, but what's the contributor agreement I should add?

**Comment by abompard** [comment]
It's the Developer Certificate of Origin, it's all explained here: https://noggin-aaa.readthedocs.io/en/latest/contributing.html#licensing

**Comment by Jibec** [comment]
Done, following: 
https://docs.weblate.org/en/latest/admin/licensing.html#contributor-agreement

It should work with all new contributions.
I did translate one more string, Weblate squashed my commit, please 
confirm that you see the signed-off thing you expect.

**Comment by abompard** [comment]
Hmm nope I don't see any `Signed-off by` lines in the commits

**Comment by Jibec** [comment]
Le 2020-05-12 14:23, Aurélien Bompard a écrit :
> Hmm nope I don't see any Signed-off by lines in the commits

Then merge it, new Weblate PR will contain it.
I assume Weblate looses the information when squashing commits.

if you need to manually access the git repo, you can access the Weblate 
git repo with: 
https://translate.fedoraproject.org/git/fedora-infra/noggin/
I locked it in weblate so translators can't change it anymore

please ping me once done, so I unlock the component

**Comment by abompard** [comment]
@Jibec OK merged.

**Pull request merged**
