### PR TITLE
Add RSS field in edit user page

### PR DESCRIPTION
**Pull request by phsmoura**
This is a working in progress for issue [1155](https://github.com/fedora-infra/noggin/issues/1155)

When I try to submit the form get the following error:
`Unknown option: fasrssurl`

Any tips how to fix this?

### CODE REVIEW

**Comment by abompard** [comment]
Yes, you need to add the attribute to our objectClass in https://github.com/fedora-infra/freeipa-fas. Feel free to ask if you need any help.

**Comment by phsmoura** [comment]
Also opened a PR in freeipa here: https://github.com/fedora-infra/freeipa-fas/pull/143

**Review by abompard — CHANGES_REQUESTED** [review]
Looks good! And I tested it, it works fine :-)
Two minor remarks:
- could you please add "`Fixes: #1155`" to your commit message
- please add a news fragment as described [in the contributor doc](https://noggin-aaa.readthedocs.io/en/latest/contributing.html#release-notes)

**Comment by phsmoura** [comment]
Done! Thanks for reviewing it :)

**Review by abompard — CHANGES_REQUESTED** [review]
Same here, the news fragment should contain the line that will be added to the changelog. Something like "Add the RSS URL to the user profile", for example.

**Review by abompard — APPROVED** [review]

**Pull request merged**
