### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by ryanlerch**
a WIP PR, requesting comments.

I tried to stub out the files for the tests, as well as adding a few basic non-authed tests.

tried to split the commits out a bit, but happy to squash (or break them up further if needed)

### CODE REVIEW

**Review by abompard — CHANGES_REQUESTED** [review]
The `securitas/tests/utility/` directory should be under `securitas/tests/unit/` like the rest.

**Comment by abompard** [comment]
I've added a commit which integrates VCR and contains one unit tests that demonstrates it.

**Comment by ryanlerch** [comment]
@abompard added some more tests too.

**Review by abompard — APPROVED** [review]
Yep I think it's a good structure, we can merge than and improve upon it with more tests.

**Pull request merged**
