### PR TITLE
change project references to noggin

### LINKED ISSUE #142: Rename the project to a legally available name
Securitas is not available as a name for this project, we need to rename it. What needs to be renamed:

- [x] the github project
- [x] all references of securitas in the source code
- [x] the Centos CI project
- [x] the mergify integration
- [x] the readthedocs integration and associated webhooks
- [x] the LGTM / Sonarqube integrations
- [ ] the Communishift project and associated webhooks
- [x] the bot that publishes on the IRC channel

### PR DESCRIPTION
**Pull request by StephenCoady**
Signed-off-by: Stephen Coady <scoady@redhat.com>

resolves: #142

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Review by ryanlerch — DISMISSED** [review]
LGTM.

**Comment by Conan-Kudo** [comment]
@StephenCoady Shouldn't you just delete the `.travis.yml` since it's unused?

**Comment by Conan-Kudo** [comment]
@StephenCoady Actually, to be clear, with deleting `.containerdev-public`, the `.travis.yml` is busted.

**Comment by StephenCoady** [comment]
@Conan-Kudo yep, we weren't using it anyway and we use a different environment so I've just deleted it.

**Review by Conan-Kudo — APPROVED** [review]

**Pull request closed without merging**
