### PR TITLE
Change name to Noggin.

### PR DESCRIPTION
**Pull request by ryanlerch**
Signed-off-by: Ryan Lerch <rlerch@redhat.com>

### CODE REVIEW

**Review by relrod — COMMENTED** [review]
I still use the `.containerdev-public` files for my dev env... Plz2not delete them? :)

**Comment by ryanlerch** [comment]
> I still use the `.containerdev-public` files for my dev env... Plz2not delete them? :)

Sorry about that! no longer removing it in the commit

**Comment by ryanlerch** [comment]
also removed a few 'sēcūritās' from the theme.

**Comment by relrod** [comment]
> > I still use the `.containerdev-public` files for my dev env... Plz2not delete them? :)
> 
> Sorry about that! no longer removing it in the commit

No worries, I have a bit of a weird setup and never migrated to the new setup after I forked to fedora-infra, because, well I kinda like my setup ;). Thanks for accommodating :)

**Comment by abompard** [comment]
This is related to #142.

**Review by abompard — DISMISSED** [review]

**Review by Conan-Kudo — APPROVED** [review]
What's old is new again... 🤣

**Pull request closed without merging**
